const gallery={items:[],index:0};
function openGallery(items,title,start=0){gallery.items=items;gallery.index=start;document.getElementById('modalTitle').textContent=title;document.getElementById('modal').classList.add('open');document.body.style.overflow='hidden';renderGallery()}
function renderGallery(){const i=gallery.index, items=gallery.items;document.getElementById('modalImg').src=items[i];document.getElementById('modalCount').textContent=(i+1)+' / '+items.length;const th=document.getElementById('thumbs');th.innerHTML=items.map((s,n)=>`<button class="${n===i?'active':''}" onclick="gallery.index=${n};renderGallery()"><img src="${s}" alt=""></button>`).join('')}
function closeGallery(){document.getElementById('modal').classList.remove('open');document.body.style.overflow=''}
document.getElementById('close').onclick=closeGallery;document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeGallery()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeGallery();if(e.key==='ArrowRight'&&gallery.items.length){gallery.index=(gallery.index+1)%gallery.items.length;renderGallery()}if(e.key==='ArrowLeft'&&gallery.items.length){gallery.index=(gallery.index-1+gallery.items.length)%gallery.items.length;renderGallery()}});
function setupFilters(){document.querySelectorAll('.filters').forEach(bar=>{bar.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{bar.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const target=bar.id==='designFilters'?document.getElementById('designList'):document.getElementById('stylingList');const f=btn.dataset.filter;target.querySelectorAll('.project-card').forEach(card=>card.style.display=(f==='all'||card.dataset.cat===f)?'block':'none')}))})}
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(e=>io.observe(e));setupFilters();
const header=document.getElementById('header');window.addEventListener('scroll',()=>{header.style.boxShadow=scrollY>20?'0 8px 30px rgba(32,32,32,.06)':'none';const h=document.documentElement.scrollHeight-innerHeight;document.getElementById('progress').style.width=(h?scrollY/h*100:0)+'%'});
const menu=document.getElementById('menu'),nav=document.getElementById('nav');
const disciplineDropdown=document.getElementById('disciplineDropdown');
const disciplineToggle=disciplineDropdown?.querySelector('.nav-dropdown-toggle');
menu.onclick=()=>nav.classList.toggle('open');
if(disciplineToggle){disciplineToggle.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();const open=disciplineDropdown.classList.toggle('open');disciplineToggle.setAttribute('aria-expanded',open?'true':'false')})}
nav.querySelectorAll('.nav-dropdown-menu a, nav > a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');disciplineDropdown?.classList.remove('open');disciplineToggle?.setAttribute('aria-expanded','false')}));
document.addEventListener('click',e=>{if(disciplineDropdown&&!disciplineDropdown.contains(e.target)){disciplineDropdown.classList.remove('open');disciplineToggle?.setAttribute('aria-expanded','false')}});
