name: Sync Basma Fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync fork
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.FORK_TOKEN }}
          script: |
            await github.rest.repos.merge({
              owner: 'BasmaElHosseiny',
              repo: 'ww-Portfolio',
              base: 'main',
              head: 'aliaasaudi14:main',
              commit_message: 'Sync with original repository'
            });
